### ISSUE TITLE
Does not work on Angular 7

### ISSUE THREAD

**Issue by leandrogtcampos** [fcorti/adf-pentaho-project#6]
Hi Francesco!

I am trying to use the pentaho-dashboard-project with Angular 7 and getting the errors bellow, could you help me?

Error: C:\workspace\MyProject\node_modules\pentaho-dashboard\src\app\pentaho-dashboard\pentaho-dashboard.component.ts is m

issing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library
. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Forma
t (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\workspace\MyProject\node_modules\@ngtools\webpack\src\angular_compiler_pl
ugin.js:752:23)
    at plugin.done.then (C:\workspace\MyProject\openbi\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
ERROR in ./node_modules/pentaho-dashboard/src/app/shared/pentaho-dashboard.service.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\workspace\MyProject\node_modules\pentaho-dashboard\src\app\shared\pentaho-dashboard.service.ts is missing from t
he TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library
. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Forma
t (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\workspace\MyProject\node_modules\@ngtools\webpack\src\angular_compiler_pl
ugin.js:752:23)
    at plugin.done.then (C:\workspace\MyProject\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by fcorti** [comment]
Hi Leandro,

Any luck with this upgrade?

**Comment by leandrogtcampos** [comment]
Hi Francesco, how are you?

As I was runing out of time, I've decided to build the project using
Angular 5, and everything is working fine.

Thanks for your support!

Best regards,


*Leandro G. Teodoro Campos*
*Senior Java Software Engineer*
*+55 (31) 997862628*
LinkedIn <http://br.linkedin.com/in/leandrogtcampos>
Skype <https://is.gd/DDsl2y>


Em ter, 16 de jul de 2019 às 16:58, Francesco Corti <
notifications@github.com> escreveu:
